name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install
        run: yarn install
      - name: TSC
        run: yarn tsc:full
      - name: Prettier
        run: yarn prettier:check
      - name: ESLint
        run: yarn lint
